## Delete a patient by ID
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0OTU1ODI5NCwiZXhwIjoxNzQ5NTk0Mjk0fQ.24FlOGXyg7RtnZkN8D3kpK8SL10fJwi2WBWz7adk2XY
DELETE http://localhost:4000/patients/c1990ddb-4e58-4b94-b984-ba4710a3f0e9
Authorization: Bearer {{token}}